import requests, json

def getByIngredient(ingredient):
    data = requests.get('https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=' + ingredient)
    if data.status_code == 200 and len(data.text) > 0:
        jsonData = json.loads(data.text)
        return jsonData['drinks'] #Returnerer en liste af drinks der indeholder ingrediensen
    else:
        return []

print(getByIngredient('Vermouth'))
"""[{'strDrink': 'Addison', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg', 'idDrink': '17228'}, {'strDrink': "Hunter's Moon", 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t0iugg1509556712.jpg', 'idDrink': '17239'}, {'strDrink': 'Ziemes Martini Apfelsaft', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xnzr2p1485619687.jpg', 'idDrink': '14157'}]"""

#print(getById('11007'))
"""[{'idDrink': '11007', 'strDrink': 'Margarita', 'strDrinkAlternate': None, 'strDrinkES': None, 'strDrinkDE': None, 'strDrinkFR': None, 'strDrinkZH-HANS': None, 'strDrinkZH-HANT': None, 'strTags': 'IBA,ContemporaryClassic', 'strVideo': None, 'strCategory': 'Ordinary Drink', 'strIBA': 'Contemporary Classics', 'strAlcoholic': 'Alcoholic', 'strGlass': 'Cocktail glass', 'strInstructions': 'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.', 'strInstructionsES': None, 'strInstructionsDE': 'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.', 'strInstructionsFR': None, 'strInstructionsZH-HANS': None, 'strInstructionsZH-HANT': None, 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg', 'strIngredient1': 'Tequila', 'strIngredient2': 'Triple sec', 'strIngredient3': 'Lime juice', 'strIngredient4': 'Salt', 'strIngredient5': None, 'strIngredient6': None, 'strIngredient7': None, 'strIngredient8': None, 'strIngredient9': None, 'strIngredient10': None, 'strIngredient11': None, 'strIngredient12': None, 'strIngredient13': None, 'strIngredient14': None, 'strIngredient15': None, 'strMeasure1': '1 1/2 oz ', 'strMeasure2': '1/2 oz ', 'strMeasure3': '1 oz ', 'strMeasure4': None, 'strMeasure5': None, 'strMeasure6': None, 'strMeasure7': None, 'strMeasure8': None, 'strMeasure9': None, 'strMeasure10': None, 'strMeasure11': None, 'strMeasure12': None, 'strMeasure13': None, 'strMeasure14': None, 'strMeasure15': None, 'strImageSource': 'https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg', 'strImageAttribution': 'Cocktailmarler', 'strCreativeCommonsConfirmed': 'Yes', 'dateModified': '2015-08-18 14:42:59'}]"""
